### ISSUE TITLE
It fails right after loging in

### ISSUE THREAD

**Issue by pierreminiggio** [fawazahmed0/youtube-uploader#12]
It successfully logs in (Changed headless to "false" to see what's going on), but then fails to start he upload process, here is my console trace :

TimeoutError: waiting for XPath `//*[normalize-space(text())='Select files']` failed: timeout 60
000ms exceeded
    at new WaitTask (F:\dev\youtube-uploader\node_modules\puppeteer\lib\cjs\puppeteer\common\DOM
World.js:509:34)
    at DOMWorld.waitForXPath (F:\dev\youtube-uploader\node_modules\puppeteer\lib\cjs\puppeteer\c
ommon\DOMWorld.js:445:26)
    at Frame.waitForXPath (F:\dev\youtube-uploader\node_modules\puppeteer\lib\cjs\puppeteer\comm
on\FrameManager.js:865:51)
    at Page.waitForXPath (F:\dev\youtube-uploader\node_modules\puppeteer\lib\cjs\puppeteer\commo
n\Page.js:2289:33)
    at login (F:\dev\youtube-uploader\upload.js:107:21)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async upload (F:\dev\youtube-uploader\upload.js:52:5)
Error: Protocol error (Runtime.callFunctionOn): Target closed.
    at F:\dev\youtube-uploader\node_modules\puppeteer\lib\cjs\puppeteer\common\Connection.js:217
:63
    at new Promise (<anonymous>)
    at CDPSession.send (F:\dev\youtube-uploader\node_modules\puppeteer\lib\cjs\puppeteer\common\
Connection.js:216:16)
    at next (F:\dev\youtube-uploader\node_modules\puppeteer-extra-plugin-stealth\evasions\source
url\index.js:32:41)
    at CDPSession.send (F:\dev\youtube-uploader\node_modules\puppeteer-extra-plugin-stealth\evas
ions\sourceurl\index.js:65:16)
    at ExecutionContext._evaluateInternal (F:\dev\youtube-uploader\node_modules\puppeteer\lib\cj
s\puppeteer\common\ExecutionContext.js:204:50)
    at ExecutionContext.evaluateHandle (F:\dev\youtube-uploader\node_modules\puppeteer\lib\cjs\p
uppeteer\common\ExecutionContext.js:155:21)
    at WaitTask.rerun (F:\dev\youtube-uploader\node_modules\puppeteer\lib\cjs\puppeteer\common\D
OMWorld.js:532:37)
Error: Protocol error (Runtime.callFunctionOn): Session closed. Most likely the page has been cl
osed.
    at CDPSession.send (F:\dev\youtube-uploader\node_modules\puppeteer\lib\cjs\puppeteer\common\
Connection.js:208:35)
    at next (F:\dev\youtube-uploader\node_modules\puppeteer-extra-plugin-stealth\evasions\source
url\index.js:32:41)
    at CDPSession.send (F:\dev\youtube-uploader\node_modules\puppeteer-extra-plugin-stealth\evas
ions\sourceurl\index.js:65:16)
    at ExecutionContext._evaluateInternal (F:\dev\youtube-uploader\node_modules\puppeteer\lib\cj
s\puppeteer\common\ExecutionContext.js:204:50)
    at ExecutionContext.evaluateHandle (F:\dev\youtube-uploader\node_modules\puppeteer\lib\cjs\p
uppeteer\common\ExecutionContext.js:155:21)
    at WaitTask.rerun (F:\dev\youtube-uploader\node_modules\puppeteer\lib\cjs\puppeteer\common\D
OMWorld.js:532:37)

**Comment by fawazahmed0** [comment]
This package only works for English version of youtube.
I have mentioned about this [here](https://github.com/fawazahmed0/youtube-uploader#readme) (read the note2)

Go to this [link](https://youtube.com/upload) & login to your account, it should look something like this(i.e it should show Select Files button)
![Screenshot (163)](https://user-images.githubusercontent.com/20347013/124395238-97c69d00-dd20-11eb-91a2-2c03644826ed.png)

**Comment by pierreminiggio** [comment]
Hmmm. It's indeed the language cauzing that.
But the issue is that it's already in english when I log in using my browser.
But when running the script, in chromium it's in french.

**Comment by fawazahmed0** [comment]
The fix is actually simple, someone needs to add extra code during login to change the language to English(United Kingdom).
Something like this:

![Screenshot (167)](https://user-images.githubusercontent.com/20347013/124400863-41b72100-dd43-11eb-869b-aebd429be9ad.png)
![Screenshot (169)](https://user-images.githubusercontent.com/20347013/124400866-454aa800-dd43-11eb-8ecd-70eb7552b959.png)
![Screenshot (170)](https://user-images.githubusercontent.com/20347013/124400869-47146b80-dd43-11eb-8104-3842ac6c4fdf.png)

I tried doing that before, but it seems to bit tricky, so I thought I will fix this thing later.

**Comment by TentacleSama4254** [comment]
Language wouldn't be an issue if you were using Node elements isnted of onscreen Text for navigation using puppeteer tho 🤔

**Comment by pierreminiggio** [comment]
> Language wouldn't be an issue if you were using Node elements isnted of onscreen Text for navigation using puppeteer tho 🤔

If you look at Youtube's HTML, it's quite hard to discriminate an element with a simple CSS Selector, if you wanna do it with a node element, you're either forced to use a quite complex selector, or use an xpath, which makes the code vulnerable to a parent element or previous sibling changing.

So I don't think it's actually better to use node elements, both way of doing it have advantages and drawbacks.

Either way, Language might not be an issue anymore after this PR got merged : https://github.com/fawazahmed0/youtube-uploader/pull/16
