### ISSUE TITLE
Error with the tags

### ISSUE THREAD

**Issue by TentacleSama4254** [fawazahmed0/youtube-uploader#13]
e_modules/youtube-videos-uploader/node_modules/puppeteer/lib/cjs/puppeteer/common/assert.js:26
        throw new Error(message);
              ^

Error: No node found for selector: [placeholder="Add tag"]
    at Object.assert (/home/tentaclesama/Downloads/Files/rAqua/node_modules/youtube-videos-uploader/node_modules/puppeteer/lib/cjs/puppeteer/common/assert.js:26:15)
    at DOMWorld.focus (/home/tentaclesama/Downloads/Files/rAqua/node_modules/youtube-videos-uploader/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:283:21)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
    at async uploadVideo (/home/tentaclesama/Downloads/Files/rAqua/node_modules/youtube-videos-uploader/upload.js:228:5)
    at async upload (/home/tentaclesama/Downloads/Files/rAqua/node_modules/youtube-videos-uploader/upload.js:60:18)

**Comment by fawazahmed0** [comment]
Please reopen this issue, if you still face this problem in latest version
