### ISSUE TITLE
video not publishing

### ISSUE THREAD

**Issue by bsde1234** [fawazahmed0/youtube-uploader#170]
Video uploaded and piracy check passed, but the video shows as draft, it is not giving visibility public and publish. Title and description also not updating.

```
const { upload } = require('youtube-videos-uploader'); //vanilla javascript

const credentials = { email: 'xxxxxx@gmail.com', pass: '^xxxxxxxxx', recoveryemail: 'xxxx@gmail.com' }

const video1 = { path: '../../pdfs/320435359.mp4', title: 'title 1', description: 'description 1', channelName: 'Kerala PSC', publishType: 'public', skipProcessingWait: true, onProgress: (progress) => { console.log('progress', progress) } }

const onVideoUploadSuccess = (videoUrl) => {
}
// const video2 = { path: 'video2.mp4', title: 'title 2', description: 'description 2', thumbnail:'thumbnail.png', language: 'english', tags: ['video', 'github'], playlist: 'playlist name', channelName: 'Channel Name', onSuccess:onVideoUploadSuccess, skipProcessingWait: true, onProgress: (progress) => { console.log('progress', progress) } }


upload (credentials, [video1]).then(console.log)

// upload (credentials, [video1, video2], {headless:false}).then(console.log)
```

Also I get error like,
```
progress { progress: 0, stage: 0 }
(node:28389) UnhandledPromiseRejectionWarning: TypeError: Promise.any is not a function
    at /var/www/html/yt-up/youtube-uploader/node_modules/youtube-videos-uploader/dist/upload.js:162:44
    at Generator.next (<anonymous>)
    at fulfilled (/var/www/html/yt-up/youtube-uploader/node_modules/youtube-videos-uploader/dist/upload.js:5:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:28389) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:28389) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
progress { progress: 16, stage: 0 }
progress { progress: 33, stage: 0 }
progress { progress: 49, stage: 0 }
progress { progress: 82, stage: 0 }
progress { progress: 100, stage: 0 }
progress { progress: 95, stage: 0 }
progress { progress: 0, stage: 0 }
progress { progress: 1, stage: 0 }
progress { progress: 2, stage: 0 }
progress { progress: 3, stage: 0 }
```

**Comment by bsde1234** [comment]
Hi, any fix?

**Comment by bsde1234** [comment]
fixed by updating node
