### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: Failed to launch the browser process!

### ISSUE THREAD

**Issue by bsde1234** [fawazahmed0/youtube-uploader#171]
When I run node upload.js, I get
```
(node:31525) UnhandledPromiseRejectionWarning: Error: Failed to launch the browser process!
[1105/062554.042770:FATAL:zygote_host_impl_linux.cc(117)] No usable sandbox! Update your kernel or see https://chromium.googlesource.com/chromium/src/+/main/docs/linux/suid_sandbox_development.md for more information on developing with the SUID sandbox. If you want to live dangerously and need an immediate workaround, you can try using --no-sandbox.
#0 0x5628a0282339 base::debug::CollectStackTrace()
#1 0x5628a01f8f23 base::debug::StackTrace::StackTrace()
#2 0x5628a01f6070 logging::LogMessage::~LogMessage()
#3 0x56289e1f6c2b content::ZygoteHostImpl::Init()
#4 0x56289fd73c0f content::ContentMainRunnerImpl::Initialize()
#5 0x56289fd71bfd content::RunContentProcess()
#6 0x56289fd71d4e content::ContentMain()
#7 0x56289fdc920a headless::(anonymous namespace)::RunContentMain()
#8 0x56289fdc8f15 headless::HeadlessShellMain()
#9 0x56289c6aa1e3 ChromeMain
#10 0x7f87ff7e009b __libc_start_main
#11 0x56289c6aa02a _start



TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (/var/www/html/yt-up/youtube-uploader/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:286:20)
    at Interface.listeners (/var/www/html/yt-up/youtube-uploader/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:274:24)
    at Interface.emit (events.js:203:15)
    at Interface.close (readline.js:397:8)
    at Socket.onend (readline.js:173:10)
    at Socket.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:31525) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:31525) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by bsde1234** [comment]
Fixed with args --no-sandbox
