### ISSUE TITLE
Issue with Monetization

### ISSUE THREAD

**Issue by renanrox** [fawazahmed0/youtube-uploader#174]
the script works perfectly on my low subs channel, when i tried to use on my monetized channed, i got a this:

\node_modules\puppeteer\lib\cjs\puppeteer\common\JSHandle.js:467
            throw new Error('Node is either not clickable or not an HTMLElement');
                  ^

Error: Node is either not clickable or not an HTMLElement
    at ElementHandle.clickablePoint (E:\PROJETO247\canalrox\node_modules\puppeteer\lib\cjs\puppeteer\common\JSHandle.js:467:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ElementHandle.click (E:\PROJETO247\canalrox\node_modules\puppeteer\lib\cjs\puppeteer\common\JSHandle.js:539:26)

Node.js v18.12.1

after some headless: false attempts, i realize it stops when reach the monetization tab.

anyone who use got the same issue??

**Comment by ClassAxion** [comment]
I got the same problem today when my channel got monetized. 
I will make PR with this feature soon.

**Comment by ClassAxion** [comment]
https://github.com/fawazahmed0/youtube-uploader/pull/203
