### ISSUE TITLE
Cannot read properties of undefined (reading 'click')

### ISSUE THREAD

**Issue by MDxWARRIORxOP** [fawazahmed0/youtube-uploader#177]
{ progress: 0, stage: 0 }
{ progress: 4, stage: 0 }
{ progress: 24, stage: 0 }
{ progress: 28, stage: 0 }
{ progress: 55, stage: 0 }
{ progress: 67, stage: 0 }
{ progress: 95, stage: 0 }
{ progress: 100, stage: 0 }
{ progress: 0, stage: 1 }
{ progress: 100, stage: 2 }
D:\Learning-Nodejs\YoutubeShortsGenerator\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:286
        throw new Error('Evaluation failed: ' + (0, util_js_1.getExceptionMessage)(exceptionDetails));
              ^

Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'click')
    at pptr://__puppeteer_evaluation_script__:1:13
    at ExecutionContext._ExecutionContext_evaluate (D:\Learning-Nodejs\YoutubeShortsGenerator\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:286:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ExecutionContext.evaluate (D:\Learning-Nodejs\YoutubeShortsGenerator\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:117:16) 

Node.js v19.1.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

this error occurs while commenting.

**Comment by pierreminiggio** [comment]
Should give context, how to reproduce, etc.

**Comment by MDxWARRIORxOP** [comment]
sorry, heres my code:
```js
await upload(config.YOUTUBE_CREDENTIALS, [video]).then((link) => {
    const comment1 = {
      link,
      comment:
        "e",
    };

    comment(config.YOUTUBE_CREDENTIALS, [comment1]).then(console.log);

    console.log("Shutting Down.");
  });

**Comment by LevButkovskiy** [comment]
+1. Its going on because on upload the language does not change and cannot find the desired button

**Comment by LevButkovskiy** [comment]
update*, sorry
on upload all its ok
