### ISSUE TITLE
Error: Protocol error (Runtime.callFunctionOn): Session closed. Most likely the page has been closed.

### ISSUE THREAD

**Issue by Aqvdrt** [fawazahmed0/youtube-uploader#189]
When uploading a video before last one is finished, the process will keep throwing the same error. As is shown below.

Error: Protocol error (Runtime.callFunctionOn): Session closed. Most likely the page has been closed.
        at CDPSession.send (/Users/dengyu/projects/jodo-increase-smb/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:255:35)
        at next (/Users/dengyu/projects/jodo-increase-smb/node_modules/puppeteer-extra-plugin-stealth/evasions/sourceurl/index.js:34:41)
        at CDPSession.send (/Users/dengyu/projects/jodo-increase-smb/node_modules/puppeteer-extra-plugin-stealth/evasions/sourceurl/index.js:75:16)
        at ExecutionContext._ExecutionContext_evaluate (/Users/dengyu/projects/jodo-increase-smb/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:268:46)
        at ExecutionContext.evaluate (/Users/dengyu/projects/jodo-increase-smb/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:117:113)
        at DOMWorld.evaluate (/Users/dengyu/projects/jodo-increase-smb/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:206:24)

**Comment by ngoanpv** [comment]
Hi @Aqvdrt, do you have any solution on that?

**Comment by Aqvdrt** [comment]
您的来件我已收到。I‘ve received your e-mail.            ---dy
