### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'includes')

### ISSUE THREAD

**Issue by michaltrabski** [fawazahmed0/youtube-uploader#210]
TypeError: Cannot read properties of undefined (reading 'includes')
    at uploadVideo (C:\Users\mitr\Desktop\michal\NODE\upload-to-youtube\node_modules\youtube-videos-uploader\src\upload.ts:87:29)   
    at upload (C:\Users\mitr\Desktop\michal\NODE\upload-to-youtube\node_modules\youtube-videos-uploader\src\upload.ts:60:32)        
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by haupt-pascal** [comment]
I have currently the same problem, the error said this while setting the title and aborted the upload then.

**Comment by haupt-pascal** [comment]
I have currently the same problem, the error said this while setting the title and aborted the upload then.

**Comment by haupt-pascal** [comment]
Is this a known problem? @fawazahmed0
