### ISSUE TITLE
Captcha (Error)

### ISSUE THREAD

**Issue by haupt-pascal** [fawazahmed0/youtube-uploader#218]
I am encountering the error, that a captcha is showing while I am trying zu login.

Error: Recaptcha found
scheduler       |         at login (/home/node/app/node_modules/youtube-videos-uploader/src/upload.ts:1119:19)
scheduler       |         at processTicksAndRejections (node:internal/process/task_queues:95:5)
scheduler       |         at loadAccount (/home/node/app/node_modules/youtube-videos-uploader/src/upload.ts:896:13)
scheduler       |         at upload (/home/node/app/node_modules/youtube-videos-uploader/src/upload.ts:61:9)
scheduler       | [12:50:20.649] WARN (adonis_app/1): pino.final with prettyPrint does not support flushing
scheduler       | /home/node/app/node_modules/youtube-videos-uploader/dist/upload.js:916
scheduler       |             throw new Error('Recaptcha found');
scheduler       |                   ^
scheduler       | 
scheduler       | Error: Recaptcha found
scheduler       |     at login (/home/node/app/node_modules/youtube-videos-uploader/src/upload.ts:1119:19)
scheduler       |     at processTicksAndRejections (node:internal/process/task_queues:95:5)
scheduler       |     at loadAccount (/home/node/app/node_modules/youtube-videos-uploader/src/upload.ts:896:13)
scheduler       |     at upload (/home/node/app/node_modules/youtube-videos-uploader/src/upload.ts:61:9)
scheduler       | 
scheduler       | Node.js v18.16.0

I thought that my IP was maybe blocked, but another channel works fine with the upload. Is there any way to fix this from my side?

**Comment by MDxWARRIORxOP** [comment]
I am getting the same error, any updates?
