### ISSUE TITLE
How can I use this on a folder of videos?

### ISSUE THREAD

**Issue by Auditormadness9** [fawazahmed0/youtube-uploader#230]

**Comment by Auditormadness9** [comment]
Goes to youtube and returns this:

```
Error: net::ERR_ABORTED at https://www.youtube.com/upload?persist_gl=1&gl=US&persist_hl=1&hl=en
    at navigate (S:\yt\node_modules\puppeteer\lib\cjs\puppeteer\common\FrameManager.js:195:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async FrameManager.navigateFrame (S:\yt\node_modules\puppeteer\lib\cjs\puppeteer\common\FrameManager.js:171:21)
    at async Frame.goto (S:\yt\node_modules\puppeteer\lib\cjs\puppeteer\common\FrameManager.js:584:16)
    at async Page.goto (S:\yt\node_modules\puppeteer\lib\cjs\puppeteer\common\Page.js:1109:16)
    at async changeHomePageLangIfNeeded (S:\yt\node_modules\youtube-videos-uploader\dist\upload.js:847:9)
    at async loadAccount (S:\yt\node_modules\youtube-videos-uploader\dist\upload.js:791:9)
    at async upload (S:\yt\node_modules\youtube-videos-uploader\dist\upload.js:46:9)
Error: net::ERR_ABORTED at https://www.youtube.com/upload?persist_gl=1&gl=US&persist_hl=1&hl=en
    at navigate (S:\yt\node_modules\puppeteer\lib\cjs\puppeteer\common\FrameManager.js:195:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async FrameManager.navigateFrame (S:\yt\node_modules\puppeteer\lib\cjs\puppeteer\common\FrameManager.js:171:21)
    at async Frame.goto (S:\yt\node_modules\puppeteer\lib\cjs\puppeteer\common\FrameManager.js:584:16)
    at async Page.goto (S:\yt\node_modules\puppeteer\lib\cjs\puppeteer\common\Page.js:1109:16)
    at async changeHomePageLangIfNeeded (S:\yt\node_modules\youtube-videos-uploader\dist\upload.js:847:9)
    at async loadAccount (S:\yt\node_modules\youtube-videos-uploader\dist\upload.js:791:9)
    at async upload (S:\yt\node_modules\youtube-videos-uploader\dist\upload.js:46:9)
S:\yt\node_modules\puppeteer\lib\cjs\puppeteer\common\FrameManager.js:195
                    ? new Error(`${response.errorText} at ${url}`)
                      ^

Error: net::ERR_ABORTED at https://www.youtube.com/upload?persist_gl=1&gl=US&persist_hl=1&hl=en
    at navigate (S:\yt\node_modules\puppeteer\lib\cjs\puppeteer\common\FrameManager.js:195:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async FrameManager.navigateFrame (S:\yt\node_modules\puppeteer\lib\cjs\puppeteer\common\FrameManager.js:171:21)
    at async Frame.goto (S:\yt\node_modules\puppeteer\lib\cjs\puppeteer\common\FrameManager.js:584:16)
    at async Page.goto (S:\yt\node_modules\puppeteer\lib\cjs\puppeteer\common\Page.js:1109:16)
    at async login (S:\yt\node_modules\youtube-videos-uploader\dist\upload.js:887:5)
    at async loadAccount (S:\yt\node_modules\youtube-videos-uploader\dist\upload.js:795:9)
    at async upload (S:\yt\node_modules\youtube-videos-uploader\dist\upload.js:46:9)
    ```

**Comment by pm96** [comment]
The error message you link to is very clear about what the issue is: "Daily upload limit reached". Have you already uploaded a large amount of videos the day you had this issue?
Could it be something relating to unverified accounts?

**Comment by Auditormadness9** [comment]
> The error message you link to is very clear about what the issue is: "Daily upload limit reached". Have you already uploaded a large amount of videos the day you had this issue? Could it be something relating to unverified accounts?

right now i am verified, have not reached the daily upload limit, and still receive the abort error. It just goes to either the uplaod screen or the main youtube page and just either times out or aborts itself.

**Comment by pm96** [comment]
What is the size and length of the video. Youtube has restriction for those as well.
It goes just fine uploading the video manually?

**Comment by Auditormadness9** [comment]
65.5 MB, 14 mins, completely fine manually.

**Comment by Auditormadness9** [comment]
many other times it can't even get to that page, just launches the main page `youtube.com` and seems to have trouble finding a selector or smth, and terminates itself with the error:

```
Error: net::ERR_ABORTED at https://www.youtube.com/upload?persist_gl=1&gl=US&persist_hl=1&hl=en
    at navigate (S:\yt\node_modules\puppeteer-core\lib\cjs\puppeteer\cdp\Frame.js:175:27)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Deferred.race (S:\yt\node_modules\puppeteer-core\lib\cjs\puppeteer\util\Deferred.js:83:20)
    at async CdpFrame.goto (S:\yt\node_modules\puppeteer-core\lib\cjs\puppeteer\cdp\Frame.js:141:25)
    at async CdpPage.goto (S:\yt\node_modules\puppeteer-core\lib\cjs\puppeteer\api\Page.js:724:20)
    at async changeHomePageLangIfNeeded (S:\yt\node_modules\youtube-videos-uploader\dist\upload.js:848:9)
    at async loadAccount (S:\yt\node_modules\youtube-videos-uploader\dist\upload.js:792:9)
    at async upload (S:\yt\node_modules\youtube-videos-uploader\dist\upload.js:46:9)
Error: net::ERR_ABORTED at https://www.youtube.com/upload?persist_gl=1&gl=US&persist_hl=1&hl=en
    at navigate (S:\yt\node_modules\puppeteer-core\lib\cjs\puppeteer\cdp\Frame.js:175:27)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Deferred.race (S:\yt\node_modules\puppeteer-core\lib\cjs\puppeteer\util\Deferred.js:83:20)
    at async CdpFrame.goto (S:\yt\node_modules\puppeteer-core\lib\cjs\puppeteer\cdp\Frame.js:141:25)
    at async CdpPage.goto (S:\yt\node_modules\puppeteer-core\lib\cjs\puppeteer\api\Page.js:724:20)
    at async changeHomePageLangIfNeeded (S:\yt\node_modules\youtube-videos-uploader\dist\upload.js:848:9)
    at async loadAccount (S:\yt\node_modules\youtube-videos-uploader\dist\upload.js:792:9)
    at async upload (S:\yt\node_modules\youtube-videos-uploader\dist\upload.js:46:9)
S:\yt\node_modules\puppeteer-core\lib\cjs\puppeteer\cdp\Frame.js:175
                        ? new Error(`${response.errorText} at ${url}`)
                          ^

Error: net::ERR_ABORTED at https://www.youtube.com/upload?persist_gl=1&gl=US&persist_hl=1&hl=en
    at navigate (S:\yt\node_modules\puppeteer-core\lib\cjs\puppeteer\cdp\Frame.js:175:27)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Deferred.race (S:\yt\node_modules\puppeteer-core\lib\cjs\puppeteer\util\Deferred.js:83:20)
    at async CdpFrame.goto (S:\yt\node_modules\puppeteer-core\lib\cjs\puppeteer\cdp\Frame.js:141:25)
    at async CdpPage.goto (S:\yt\node_modules\puppeteer-core\lib\cjs\puppeteer\api\Page.js:724:20)
    at async login (S:\yt\node_modules\youtube-videos-uploader\dist\upload.js:888:5)
    at async loadAccount (S:\yt\node_modules\youtube-videos-uploader\dist\upload.js:796:9)
    at async upload (S:\yt\node_modules\youtube-videos-uploader\dist\upload.js:46:9)
    ```
