### ISSUE TITLE
video upload is getting failed on vercel(Timeout error)

### ISSUE THREAD

**Issue by virendrarajpurohit** [fawazahmed0/youtube-uploader#239]
Hi,
When we use this library on server(vercel) then video upload is getting failed after launching the browser. the error it gives is:

```
TimeoutError: waiting for selector `input[type="password"]:not([aria-hidden="true"])` failed: timeout 60000ms exceeded
    at new WaitTask (/vercel/path0/node_modules/puppeteer/lib/cjs/puppeteer/common/IsolatedWorld.js:445:34)
    at IsolatedWorld._waitForSelectorInPage (/vercel/path0/node_modules/puppeteer/lib/cjs/puppeteer/common/IsolatedWorld.js:335:26)
    at Object.internalHandler.waitFor (/vercel/path0/node_modules/puppeteer/lib/cjs/puppeteer/common/QueryHandler.js:46:83)
    at Frame.waitForSelector (/vercel/path0/node_modules/puppeteer/lib/cjs/puppeteer/common/Frame.js:420:36)
    at Page.waitForSelector (/vercel/path0/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:2318:39)
    at login (/vercel/path0/node_modules/youtube-videos-uploader/dist/upload.js:974:25)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async loadAccount (/vercel/path0/node_modules/youtube-videos-uploader/dist/upload.js:838:13)
    at async upload (/vercel/path0/node_modules/youtube-videos-uploader/dist/upload.js:52:9)
```
is the issue because of google blocking the automated usage of pupeteer. if so, then why it works perfectly on local?

**Comment by ali-kingX** [comment]
I have this issue too, just trying to upload a video with this, nothing special.

**Comment by developerfromjokela** [comment]
> Hi, When we use this library on server(vercel) then video upload is getting failed after launching the browser. the error it gives is:
> 
> ```
> TimeoutError: waiting for selector `input[type="password"]:not([aria-hidden="true"])` failed: timeout 60000ms exceeded
>     at new WaitTask (/vercel/path0/node_modules/puppeteer/lib/cjs/puppeteer/common/IsolatedWorld.js:445:34)
>     at IsolatedWorld._waitForSelectorInPage (/vercel/path0/node_modules/puppeteer/lib/cjs/puppeteer/common/IsolatedWorld.js:335:26)
>     at Object.internalHandler.waitFor (/vercel/path0/node_modules/puppeteer/lib/cjs/puppeteer/common/QueryHandler.js:46:83)
>     at Frame.waitForSelector (/vercel/path0/node_modules/puppeteer/lib/cjs/puppeteer/common/Frame.js:420:36)
>     at Page.waitForSelector (/vercel/path0/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:2318:39)
>     at login (/vercel/path0/node_modules/youtube-videos-uploader/dist/upload.js:974:25)
>     at processTicksAndRejections (node:internal/process/task_queues:96:5)
>     at async loadAccount (/vercel/path0/node_modules/youtube-videos-uploader/dist/upload.js:838:13)
>     at async upload (/vercel/path0/node_modules/youtube-videos-uploader/dist/upload.js:52:9)
> ```
> 
> is the issue because of google blocking the automated usage of pupeteer. if so, then why it works perfectly on local?

They added recaptcha prompts, that's why you get the password prompt timeout.

**Comment by virendrarajpurohit** [comment]
@developerfromjokela yes, do you know any way to by pass those recaptcha prompts.

**Comment by MDxWARRIORxOP** [comment]
So this will never work again then?
