### ISSUE TITLE
Uncaught TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by xiaoxinhuozhu** [fawazahmed0/youtube-uploader#30]
I'm new to this. Can you help me with this problem
node -v
v6.17.1
npm -v
3.10.10
`> upload (credentials,video1).then(console.log)
Promise { <pending> }
> Uncaught TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at getKeys (/root/youtubeup/youtube-uploader/node_modules/deepmerge/dist/cjs.js:61:16)
    at mergeObject (/root/youtubeup/youtube-uploader/node_modules/deepmerge/dist/cjs.js:86:2)
    at deepmerge (/root/youtubeup/youtube-uploader/node_modules/deepmerge/dist/cjs.js:117:10)
    at PuppeteerExtra.launch (/root/youtubeup/youtube-uploader/node_modules/puppeteer-extra/dist/index.cjs.js:117:19)
    at launchBrowser (/root/youtubeup/youtube-uploader/node_modules/youtube-videos-uploader/upload.js:213:29)
    at upload (/root/youtubeup/youtube-uploader/node_modules/youtube-videos-uploader/upload.js:77:9)
> `

**Comment by fawazahmed0** [comment]
try

upload (credentials,[video1],{}).then(console.log)

also update nodejs, it seems old

________________________________
From: xiaoxinhuozhu ***@***.***>
Sent: Saturday, August 14, 2021 10:42 AM
To: fawazahmed0/youtube-uploader ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [fawazahmed0/youtube-uploader] Uncaught TypeError: Cannot convert undefined or null to object (#30)


I'm new to this. Can you help me with this problem
node -v
v6.17.1
npm -v
3.10.10
`> upload (credentials,video1).then(console.log)
Promise { }

Uncaught TypeError: Cannot convert undefined or null to object
at Function.keys ()
at getKeys (/root/youtubeup/youtube-uploader/node_modules/deepmerge/dist/cjs.js:61:16)
at mergeObject (/root/youtubeup/youtube-uploader/node_modules/deepmerge/dist/cjs.js:86:2)
at deepmerge (/root/youtubeup/youtube-uploader/node_modules/deepmerge/dist/cjs.js:117:10)
at PuppeteerExtra.launch (/root/youtubeup/youtube-uploader/node_modules/puppeteer-extra/dist/index.cjs.js:117:19)
at launchBrowser (/root/youtubeup/youtube-uploader/node_modules/youtube-videos-uploader/upload.js:213:29)
at upload (/root/youtubeup/youtube-uploader/node_modules/youtube-videos-uploader/upload.js:77:9)
`
