### ISSUE TITLE
Showing captcha during login

### ISSUE THREAD

**Issue by pierreminiggio** [fawazahmed0/youtube-uploader#39]
I've one my Youtube Accounts that stoped uploading and his stuck on this window :  
![image](https://user-images.githubusercontent.com/35456349/134088042-6518d314-bc1d-489f-966c-2b0baf09ab46.png)

My Google account settings seem correct (no recovery phone number, and 1 recovery email address)

Added some console logs to see where it goes wrong. And looks like it fails to handle the recovery email input correctly.
```console
logging in
lang
email
pass
enter
TimeoutError: waiting for selector `ytcp-uploads-dialog` failed: timeout 60000ms exceeded
    at new WaitTask (/var/www/html/youtube-poster-api/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:509:34)
    at DOMWorld.waitForSelectorInPage (/var/www/html/youtube-poster-api/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:420:26)
    at Object.internalHandler.waitFor (/var/www/html/youtube-poster-api/node_modules/puppeteer/lib/cjs/puppeteer/common/QueryHandler.js:31:77)
    at DOMWorld.waitForSelector (/var/www/html/youtube-poster-api/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:313:29)
    at Frame.waitForSelector (/var/www/html/youtube-poster-api/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:841:51)
    at Page.waitForSelector (/var/www/html/youtube-poster-api/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:2252:33)
    at login (/var/www/html/youtube-poster-api/node_modules/youtube-videos-uploader/upload.js:258:21)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async upload (/var/www/html/youtube-poster-api/node_modules/youtube-videos-uploader/upload.js:91:5)
confirming recovery email
entering recovery email adress
TimeoutError: Navigation timeout of 60000 ms exceeded
    at /var/www/html/youtube-poster-api/node_modules/puppeteer/lib/cjs/puppeteer/common/LifecycleWatcher.js:106:111
    at async FrameManager.waitForFrameNavigation (/var/www/html/youtube-poster-api/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:127:23)
    at async Frame.waitForNavigation (/var/www/html/youtube-poster-api/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:440:16)
    at async Page.waitForNavigation (/var/www/html/youtube-poster-api/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:1211:16)
    at async securityBypass (/var/www/html/youtube-poster-api/node_modules/youtube-videos-uploader/upload.js:287:5)
    at async login (/var/www/html/youtube-poster-api/node_modules/youtube-videos-uploader/upload.js:262:5)
    at async upload (/var/www/html/youtube-poster-api/node_modules/youtube-videos-uploader/upload.js:91:5)
Login failed trying again to login
lang
email
(node:1492583) UnhandledPromiseRejectionWarning: TimeoutError: Navigation timeout of 60000 ms exceeded
    at /var/www/html/youtube-poster-api/node_modules/puppeteer/lib/cjs/puppeteer/common/LifecycleWatcher.js:106:111
    at async FrameManager.waitForFrameNavigation (/var/www/html/youtube-poster-api/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:127:23)
    at async Frame.waitForNavigation (/var/www/html/youtube-poster-api/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:440:16)
    at async Page.waitForNavigation (/var/www/html/youtube-poster-api/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:1211:16)
    at async login (/var/www/html/youtube-poster-api/node_modules/youtube-videos-uploader/upload.js:242:3)
    at async upload (/var/www/html/youtube-poster-api/node_modules/youtube-videos-uploader/upload.js:96:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1492583) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1492583) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Comment by fawazahmed0** [comment]
Try with latest version, should work fine now.
Let me know, if it still doesn't work

**Comment by pierreminiggio** [comment]
It still fails :
```console
TimeoutError: Navigation timeout of 60000 ms exceeded
    at /var/www/html/youtube-poster-api/node_modules/puppeteer/lib/cjs/puppeteer/common/LifecycleWatcher.js:106:111
    at async FrameManager.waitForFrameNavigation (/var/www/html/youtube-poster-api/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:127:23)
    at async Frame.waitForNavigation (/var/www/html/youtube-poster-api/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:440:16)
    at async Page.waitForNavigation (/var/www/html/youtube-poster-api/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:1211:16)
    at async login (/var/www/html/youtube-poster-api/node_modules/youtube-videos-uploader/upload.js:251:3)
    at async upload (/var/www/html/youtube-poster-api/node_modules/youtube-videos-uploader/upload.js:90:5)
Login failed trying again to login
(node:1505016) UnhandledPromiseRejectionWarning: TimeoutError: Navigation timeout of 60000 ms exceeded
    at /var/www/html/youtube-poster-api/node_modules/puppeteer/lib/cjs/puppeteer/common/LifecycleWatcher.js:106:111
    at async FrameManager.waitForFrameNavigation (/var/www/html/youtube-poster-api/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:127:23)
    at async Frame.waitForNavigation (/var/www/html/youtube-poster-api/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:440:16)
    at async Page.waitForNavigation (/var/www/html/youtube-poster-api/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:1211:16)
    at async login (/var/www/html/youtube-poster-api/node_modules/youtube-videos-uploader/upload.js:251:3)
    at async upload (/var/www/html/youtube-poster-api/node_modules/youtube-videos-uploader/upload.js:94:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1505016) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1505016) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Comment by pierreminiggio** [comment]
![image](https://user-images.githubusercontent.com/35456349/134142022-10f02da9-bf55-4d35-94bf-7675dfeb13fe.png)
Oh fu**... It's because Youtube is asking me for a recaptcha now :'(

**Comment by fawazahmed0** [comment]
It will be tough to fix captcha issue, I assume google has marked your proxy/ip as bot, you might want to try a different [proxy/ip](https://www.google.com/search?client=firefox-b-d&q=sneakers+proxy) to overcome this issue

**Comment by pierreminiggio** [comment]
I've added a PR so that we can get warned if the script ever encounters a recaptcha : https://github.com/fawazahmed0/youtube-uploader/pull/40

**Comment by pierreminiggio** [comment]
Sent another PR so the script can end cleanly if that's the 2nd login that fails :
https://github.com/fawazahmed0/youtube-uploader/pull/41
