### ISSUE TITLE
Upload error

### ISSUE THREAD

**Issue by Inaztm** [fawazahmed0/youtube-uploader#92]
Config
```
const video = {
            path: '{filepath}',
            title: 'Test3',
            description: 'Test4'
}
```

Error:
```
Error: Node is either not clickable or not an HTMLElement
    at ElementHandle.clickablePoint (.../node_modules/puppeteer/lib/cjs/puppeteer/common/JSHandle.js:408:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async ElementHandle.click (.../node_modules/puppeteer/lib/cjs/puppeteer/common/JSHandle.js:492:26)
```

**Comment by fawazahmed0** [comment]
Paid support is available for quick resolution & help.

For paid support, please write mail to youtube-uploader@datascraping.pp.ua
